language: python
python:
  - "2.7"
env:
  # - DJANGO=1.3.1
  # - DJANGO=1.4.3
  - DJANGO=1.5.0
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q lettuce --use-mirrors
  - pip install -q lxml --use-mirrors
  - pip install -q urllib3 --use-mirrors
  - pip install -q nose --use-mirrors
  - pip install -q selenium==2.40.0 --use-mirrors
#   - pip install -q django_facebook
  - pip install -q pyvirtualdisplay
#   - pip install -q tweepy
  # - pip install pep8 --use-mirrors
  # - pip install mysql-python --use-mirrors
  # - pip install https://github.com/dcramer/pyflakes/tarball/master
  # - pip install -q -e . --use-mirrors
  #
  # Fix problem with python and threads in Travis workers
  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
before_script:
  # - "pep8 --exclude=migrations --ignore=E501,E225 src"
  # - pyflakes -x W src
  # - mysql -e 'create database mysite_db;'
  # - python manage.py syncdb --noinput
script:
  - python manage.py harvest --no-server
  # - python manage.py harvest
  # - python manage.py test
branches:
  only:
    - testing